[build]
  command = "CI= npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/@netlify/plugin-nextjs/**/*"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_render"
  status = 200
  force = true 